The-fifth-group-FinalProject/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using The_fifth_group_FinalAPI.DTOs;
using The_fifth_group_FinalAPI.Models;
using The_fifth_group_FinalProject.Helpers;
using The_fifth_group_FinalProject.Models;

namespace The_fifth_group_FinalProject.Controllers
{
    public class CartController : Controller
    {
        //public IActionResult RemoveItem(int id)
        //{
        //    //向 Session 取得商品列表
        //    List<PCartItem> cart = SessionHelper.
        //        GetObjectFromJson<List<PCartItem>>(HttpContext.Session, "cart");

        //    //用FindIndex查詢目標在List裡的位置
        //    int index = cart.FindIndex(m => m.Product.Id.Equals(id));
        //    cart.RemoveAt(index);

        //    if (cart.Count < 1)
        //    {
        //        SessionHelper.Remove(HttpContext.Session, "cart");
        //    }
        //    else
        //    {
        //        SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
        //    }

        //    return RedirectToAction("Index");
        //}

        public ActionResult Index()
        {
            return View();
        }
        //try
        //{
        //    using (var httpClient = new HttpClient())
        //    {
        //        var response = await httpClient.GetAsync($"https://localhost:7040/api/CartItems/{memberId}");
        //        response.EnsureSuccessStatusCode();

        //        var responseContent = await response.Content.ReadAsStringAsync();
        //        var cartItemsDTOs = JsonConvert.DeserializeObject<List<CartItemsDTO>>(responseContent);

        //        if (cartItemsDTOs == null)
        //        {
        //            ViewBag.Total = 0;
        //        }
        //        else
        //        {
        //            ViewBag.Total = cartItemsDTOs.Sum(m => m.Qty * m.Price);
        //        }

        //        return View(cartItemsDTOs);
        //    }

        //}
        //catch (HttpRequestException ex)
        //{
        //    return View("Error");
        //}

        ////向 Session 取得商品列表
        //List<PCartItem> CartItems = SessionHelper.
        //    GetObjectFromJson<List<PCartItem>>(HttpContext.Session, "cart");

        ////計算商品總額
        //if (CartItems != null)
        //{
        //    ViewBag.Total = CartItems.Sum(m => m.SubTotal);
        //}
        //else
        //{
        //    ViewBag.Total = 0;
        //}

        //return View(CartItems);
    }
}

The-fifth-group-FinalProject/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using System.Xml.Linq;
using The_fifth_group_FinalAPI.DTOs;
using The_fifth_group_FinalAPI.Models;
using The_fifth_group_FinalProject.Helpers;
using The_fifth_group_FinalProject.Models;
using static NuGet.Packaging.PackagingConstants;

namespace The_fifth_group_FinalProject.Controllers
{
    public class OrdersController : Controller
    {
        // GET: OrdersController
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Confirm()
        {
            return View();
        }
        public async Task<ActionResult> Products(int id)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.GetAsync($"https://localhost:7040/api/Orders/PayInfo/{id}");
                    response.EnsureSuccessStatusCode();

                    var responseContent = await response.Content.ReadAsStringAsync();
                    var data = JsonConvert.DeserializeObject<PayInfoDto>(responseContent);

                    if (data == null)
                    {
                        return View("Error");
                    }

                    return View(data);
                }
            }
            catch (HttpRequestException ex)
            {
                return View("Error");
            }
        }

        // GET: OrdersController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public IActionResult Checkout()
        {
            return View();
        }

        // 新增訂單到資料庫
        [HttpPost]
        public async Task<IActionResult> CreateOrder(Order order)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.GetAsync($"https://localhost:7040/api/CartItems/{order.MemberId}");
                    response.EnsureSuccessStatusCode();

                    var responseContent = await response.Content.ReadAsStringAsync();
                    var data = JsonConvert.DeserializeObject<List<CartItemsDTO>>(responseContent);

                    if (data == null)
                    {
                        return View("Error");
                    }
                    order.OrderItem = data.Select(ci => new OrderItem
                    {
                        ProductName = ci.ProductName,
                        Amount = ci.Qty,
                        SubTotal = ci.Price,
                    }).ToList();

                    var orders = new Orders()
                    {
                        MemberId = order.MemberId,
                        OrderNumber = Guid.NewGuid().ToString("N"),
                        CreateAt = DateTime.Now,
                        TradeStatus = 0,
                        OrderType = 1,
                        OrderStatus = 0,
                        Amount = order.OrderItem.Sum(ci => ci.SubTotal * ci.Amount),
                        OrderContent = JsonConvert.SerializeObject(order.OrderItem),
                        ShippingMethod = order.ShippingMethod,
                        OrderAddress = order.OrderAddress,

                    };

                    var content = new StringContent(
                        JsonConvert.SerializeObject(orders),
                        Encoding.UTF8,
                        "application/json"
                    );

                    var url = "https://localhost:7040/api/Orders";

                    var res = await httpClient.PostAsync(url, content);

                    if (res.IsSuccessStatusCode)
                    {
                        var resContent = await res.Content.ReadAsStringAsync();
                        var result = JsonConvert.DeserializeObject<Orders>(resContent);

                        var delrep = await httpClient.DeleteAsync($"https://localhost:7040/api/Orders/ClearCart/{order.MemberId}");
                        if (response.IsSuccessStatusCode)
                        {
                            return RedirectToAction("ReviewOrder", new { Id = result.Id });
                        }
                        else
                        {
                            return StatusCode((int)response.StatusCode);
                        }
                    }
                    else
                    {
                        throw new Exception($"Failed to create order: {res.ReasonPhrase}");
                    }
                }
            }
            catch (HttpRequestException ex)
            {
                return View("Checkout");
            }
        }

        public async Task<IActionResult> ReviewOrder(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.GetAsync($"https://localhost:7040/api/Orders/{id}");
                    response.EnsureSuccessStatusCode();

                    var responseContent = await response.Content.ReadAsStringAsync();
                    var data = JsonConvert.DeserializeObject<Order>(responseContent);

                    if (data == null)
                    {
                        return View("Error");
                    }

                    data.OrderItem = JsonConvert.DeserializeObject<List<OrderItem>>(data.OrderContent);
                    ViewBag.orderItems = data.OrderItem;

                    return View(data);
                }
            }
            catch (HttpRequestException ex)
            {
                return View("Error");
            }
        }

        // 付款
        public async Task<IActionResult> Payment(int? id, bool isSuccess)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (isSuccess)
            {
                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.PutAsync($"https://localhost:7040/api/Orders/IsPaid/{id}", null);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

The-fifth-group-FinalProject/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;

namespace The_fifth_group_FinalProject.Controllers
{
    public class ProductsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult commodity(int id)
        {
            return View();
        }
        public IActionResult Test()
        {
            return View();
        }
    }
}

The-fifth-group-FinalProject/Views/Cart/Index.cshtml
<style>
    .progressbar {
        counter-reset: step;
    }

        .progressbar li {
            list-style-type: none;
            width: 25%;
            float: left;
            font-size: 12px;
            position: relative;
            text-align: center;
            text-transform: uppercase;
            color: #7d7d7d;
        }

            .progressbar li:before {
                width: 30px;
                height: 30px;
                content: counter(step);
                counter-increment: step;
                line-height: 30px;
                border: 2px solid #7d7d7d;
                display: block;
                text-align: center;
                margin: 0 auto 10px auto;
                border-radius: 50%;
                background-color: white;
            }

            .progressbar li:after {
                width: 100%;
                height: 2px;
                content: '';
                position: absolute;
                background-color: #7d7d7d;
                top: 15px;
                left: -50%;
                z-index: -1;
            }

            .progressbar li:first-child:after {
                content: none;
            }

            .progressbar li.active {
                color: green;
            }

                .progressbar li.active:before {
                    border-color: #55b776;
                }

                .progressbar li.active + li:after {
                    background-color: #55b776;
                }

                
</style>

<div id="app">
    <div>
        <p>　</p>
        <ul class="progressbar">
            <li class="active">購物車</li>
            <li>訂單資料</li>
            <li>建立訂單</li>
            <li>付款</li>
        </ul>
        <p>　</p>
        <p>　</p>
    </div>

    <div class="card shadow rounded">
        <h5 class="card-header">購物車</h5>
        <div class="card-body">
            <template v-if="cartItems.length > 0">
                <table class="table">
                    <thead class="table-borderless">
                        <tr>
                            <th></th>
                            <th>商品名稱</th>
                            <th>單價</th>
                            <th>數量</th>
                            <th>小計</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(item, index) in cartItems" :key="index">
                            <td class="text-center">
                                <img :src="item.imageUrl" height="30" />
                            </td>
                            <td>{{ item.productName }}</td>
                            <td>{{ item.price }}</td>
                            <td>{{ item.qty }}</td>
                            <td>{{ item.subtotal }}</td>
                            <td>
                              <a class="btn btn-sm btn-danger" @@click="removeItem(item.id)">刪除</a>
                            </td> 
                        </tr>
                    </tbody>
                </table>
            </template>
            <p v-else class="text-center text-dark">購物車內尚無商品</p>
            <hr />
            <div class="row">
                <div class="col-4 justify-content-around">
                    <div class="input-group input-group-sm mb-2">
                        <span style="padding-top:3px">優惠碼：</span>
                        <input type="text" class="form-control" placeholder="coupon" name="coupon" v-model="coupon" />
                    </div>
                </div>
                <div class="col text-right pr-5">
                    <h5>總計： ${{ total }}</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3 d-flex justify-content-end">
        <a class="btn btn-secondary mx-2 active" role="button" aria-pressed="true" asp-controller="Products" asp-action="Index">繼續購物</a>
        <a class="btn btn-primary mx-2 active" role="button" aria-pressed="true" asp-controller="Orders" asp-action="Checkout">前往結帳</a>
    </div>
</div>



@section Scripts
    {
    <script src="https://unpkg.com/vue@3.2.29/dist/vue.global.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.3.3/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/3.0.1/js.cookie.min.js"></script>
    <script>
        var webApiBaseAddress = "https://localhost:7040";
        var vueApp = {
            data() {
                return {
                    cartItems: [],
                    coupon: '',
                    total: 0,
                }
            },
            mounted: function () {
                let _this = this;
                _this.checkLogin();
                _this.getAllOrders();
            },
            methods: {
                getAllOrders: function () {
                    let _this = this;
                    let memberId = Cookies.get('MemberId');
                    axios.get(`${webApiBaseAddress}/api/CartItems/${memberId}`).then(
                        res => {
                            console.log(res.data);
                            _this.cartItems = res.data;
                            var cartItemsList = [];
                            var result = 0;
                            for (var i = 0; i < _this.cartItems.length; i++) {
                                var item = {};
                                item = _this.cartItems[i];
                                item.subtotal = item.qty * item.price;
                                cartItemsList.push(item);
                                result += item.subtotal
                            }
                            _this.cartItems = cartItemsList;
                            _this.total = result;
                        }
                    );
                },
                checkLogin: function () {
                    let memberId = Cookies.get('MemberId');
                    if (!memberId > 0) {
                        alert("請先進行登入")
                        window.location = "/home/Login";
                    }
                },
                removeItem(id) {
					axios.delete(`${webApiBaseAddress}/api/CartItems/${id}`)
						.then(response => {
                            this.getAllOrders();
							console.log("刪除 "+id);
						})
				},
            }
        }
        var app = Vue.createApp(vueApp).mount("#app");
    </script>
}